# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          export ARM_CLIENT_ID=${{ secrets.AZURE_CREDENTIALS.clientId }}
          export ARM_CLIENT_SECRET=${{ secrets.AZURE_CREDENTIALS.clientSecret }}
          export ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_CREDENTIALS.subscriptionId }}
          export ARM_TENANT_ID=${{ secrets.AZURE_CREDENTIALS.tenantId }}
          cd examples/azure-container-registry
          terraform init
          terraform plan
